name: Condo
favicon: null
layout_spectrum: 0
typography_spectrum: 0.44489
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f1e5d7'
    - '#585b60'
    - '#262320'
    - '#c6b48e'
    - '#a49c76'
  brandStrength: 0.38962560263462365
  lightness: 0.8816521211992949
  saturation: 0.032624512910842896
  rhythmicContrast: 0.4405051579233259
purpose: []
